// SPDX-License-Identifier: Apache-2.0
// Copyright (c) 2022 Dell Inc, or its subsidiaries.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.19.4
// source: backend-null.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type NullDebug struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id        int64  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name      string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	BlockSize int64  `protobuf:"varint,3,opt,name=block_size,json=blockSize,proto3" json:"block_size,omitempty"`
	NumBlocks int64  `protobuf:"varint,4,opt,name=num_blocks,json=numBlocks,proto3" json:"num_blocks,omitempty"`
	Uuid      string `protobuf:"bytes,5,opt,name=uuid,proto3" json:"uuid,omitempty"`
}

func (x *NullDebug) Reset() {
	*x = NullDebug{}
	if protoimpl.UnsafeEnabled {
		mi := &file_backend_null_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NullDebug) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NullDebug) ProtoMessage() {}

func (x *NullDebug) ProtoReflect() protoreflect.Message {
	mi := &file_backend_null_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NullDebug.ProtoReflect.Descriptor instead.
func (*NullDebug) Descriptor() ([]byte, []int) {
	return file_backend_null_proto_rawDescGZIP(), []int{0}
}

func (x *NullDebug) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *NullDebug) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *NullDebug) GetBlockSize() int64 {
	if x != nil {
		return x.BlockSize
	}
	return 0
}

func (x *NullDebug) GetNumBlocks() int64 {
	if x != nil {
		return x.NumBlocks
	}
	return 0
}

func (x *NullDebug) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

type NullDebugCreateRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Device *NullDebug `protobuf:"bytes,1,opt,name=device,proto3" json:"device,omitempty"`
}

func (x *NullDebugCreateRequest) Reset() {
	*x = NullDebugCreateRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_backend_null_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NullDebugCreateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NullDebugCreateRequest) ProtoMessage() {}

func (x *NullDebugCreateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_backend_null_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NullDebugCreateRequest.ProtoReflect.Descriptor instead.
func (*NullDebugCreateRequest) Descriptor() ([]byte, []int) {
	return file_backend_null_proto_rawDescGZIP(), []int{1}
}

func (x *NullDebugCreateRequest) GetDevice() *NullDebug {
	if x != nil {
		return x.Device
	}
	return nil
}

type NullDebugCreateResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *NullDebugCreateResponse) Reset() {
	*x = NullDebugCreateResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_backend_null_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NullDebugCreateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NullDebugCreateResponse) ProtoMessage() {}

func (x *NullDebugCreateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_backend_null_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NullDebugCreateResponse.ProtoReflect.Descriptor instead.
func (*NullDebugCreateResponse) Descriptor() ([]byte, []int) {
	return file_backend_null_proto_rawDescGZIP(), []int{2}
}

type NullDebugDeleteRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *NullDebugDeleteRequest) Reset() {
	*x = NullDebugDeleteRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_backend_null_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NullDebugDeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NullDebugDeleteRequest) ProtoMessage() {}

func (x *NullDebugDeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_backend_null_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NullDebugDeleteRequest.ProtoReflect.Descriptor instead.
func (*NullDebugDeleteRequest) Descriptor() ([]byte, []int) {
	return file_backend_null_proto_rawDescGZIP(), []int{3}
}

func (x *NullDebugDeleteRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type NullDebugDeleteResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *NullDebugDeleteResponse) Reset() {
	*x = NullDebugDeleteResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_backend_null_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NullDebugDeleteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NullDebugDeleteResponse) ProtoMessage() {}

func (x *NullDebugDeleteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_backend_null_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NullDebugDeleteResponse.ProtoReflect.Descriptor instead.
func (*NullDebugDeleteResponse) Descriptor() ([]byte, []int) {
	return file_backend_null_proto_rawDescGZIP(), []int{4}
}

type NullDebugUpdateRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Device *NullDebug `protobuf:"bytes,1,opt,name=device,proto3" json:"device,omitempty"`
}

func (x *NullDebugUpdateRequest) Reset() {
	*x = NullDebugUpdateRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_backend_null_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NullDebugUpdateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NullDebugUpdateRequest) ProtoMessage() {}

func (x *NullDebugUpdateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_backend_null_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NullDebugUpdateRequest.ProtoReflect.Descriptor instead.
func (*NullDebugUpdateRequest) Descriptor() ([]byte, []int) {
	return file_backend_null_proto_rawDescGZIP(), []int{5}
}

func (x *NullDebugUpdateRequest) GetDevice() *NullDebug {
	if x != nil {
		return x.Device
	}
	return nil
}

type NullDebugUpdateResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *NullDebugUpdateResponse) Reset() {
	*x = NullDebugUpdateResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_backend_null_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NullDebugUpdateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NullDebugUpdateResponse) ProtoMessage() {}

func (x *NullDebugUpdateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_backend_null_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NullDebugUpdateResponse.ProtoReflect.Descriptor instead.
func (*NullDebugUpdateResponse) Descriptor() ([]byte, []int) {
	return file_backend_null_proto_rawDescGZIP(), []int{6}
}

type NullDebugListRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *NullDebugListRequest) Reset() {
	*x = NullDebugListRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_backend_null_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NullDebugListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NullDebugListRequest) ProtoMessage() {}

func (x *NullDebugListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_backend_null_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NullDebugListRequest.ProtoReflect.Descriptor instead.
func (*NullDebugListRequest) Descriptor() ([]byte, []int) {
	return file_backend_null_proto_rawDescGZIP(), []int{7}
}

type NullDebugListResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Device []*NullDebug `protobuf:"bytes,1,rep,name=device,proto3" json:"device,omitempty"`
}

func (x *NullDebugListResponse) Reset() {
	*x = NullDebugListResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_backend_null_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NullDebugListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NullDebugListResponse) ProtoMessage() {}

func (x *NullDebugListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_backend_null_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NullDebugListResponse.ProtoReflect.Descriptor instead.
func (*NullDebugListResponse) Descriptor() ([]byte, []int) {
	return file_backend_null_proto_rawDescGZIP(), []int{8}
}

func (x *NullDebugListResponse) GetDevice() []*NullDebug {
	if x != nil {
		return x.Device
	}
	return nil
}

type NullDebugGetRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *NullDebugGetRequest) Reset() {
	*x = NullDebugGetRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_backend_null_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NullDebugGetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NullDebugGetRequest) ProtoMessage() {}

func (x *NullDebugGetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_backend_null_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NullDebugGetRequest.ProtoReflect.Descriptor instead.
func (*NullDebugGetRequest) Descriptor() ([]byte, []int) {
	return file_backend_null_proto_rawDescGZIP(), []int{9}
}

func (x *NullDebugGetRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type NullDebugGetResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Device *NullDebug `protobuf:"bytes,1,opt,name=device,proto3" json:"device,omitempty"`
}

func (x *NullDebugGetResponse) Reset() {
	*x = NullDebugGetResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_backend_null_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NullDebugGetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NullDebugGetResponse) ProtoMessage() {}

func (x *NullDebugGetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_backend_null_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NullDebugGetResponse.ProtoReflect.Descriptor instead.
func (*NullDebugGetResponse) Descriptor() ([]byte, []int) {
	return file_backend_null_proto_rawDescGZIP(), []int{10}
}

func (x *NullDebugGetResponse) GetDevice() *NullDebug {
	if x != nil {
		return x.Device
	}
	return nil
}

type NullDebugStatsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *NullDebugStatsRequest) Reset() {
	*x = NullDebugStatsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_backend_null_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NullDebugStatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NullDebugStatsRequest) ProtoMessage() {}

func (x *NullDebugStatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_backend_null_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NullDebugStatsRequest.ProtoReflect.Descriptor instead.
func (*NullDebugStatsRequest) Descriptor() ([]byte, []int) {
	return file_backend_null_proto_rawDescGZIP(), []int{11}
}

func (x *NullDebugStatsRequest) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type NullDebugStatsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id    int64  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Stats string `protobuf:"bytes,2,opt,name=stats,proto3" json:"stats,omitempty"`
}

func (x *NullDebugStatsResponse) Reset() {
	*x = NullDebugStatsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_backend_null_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NullDebugStatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NullDebugStatsResponse) ProtoMessage() {}

func (x *NullDebugStatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_backend_null_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NullDebugStatsResponse.ProtoReflect.Descriptor instead.
func (*NullDebugStatsResponse) Descriptor() ([]byte, []int) {
	return file_backend_null_proto_rawDescGZIP(), []int{12}
}

func (x *NullDebugStatsResponse) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *NullDebugStatsResponse) GetStats() string {
	if x != nil {
		return x.Stats
	}
	return ""
}

var File_backend_null_proto protoreflect.FileDescriptor

var file_backend_null_proto_rawDesc = []byte{
	0x0a, 0x12, 0x62, 0x61, 0x63, 0x6b, 0x65, 0x6e, 0x64, 0x2d, 0x6e, 0x75, 0x6c, 0x6c, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0e, 0x6f, 0x70, 0x69, 0x2e, 0x73, 0x74, 0x6f, 0x72, 0x61, 0x67,
	0x65, 0x2e, 0x76, 0x31, 0x22, 0x81, 0x01, 0x0a, 0x09, 0x4e, 0x75, 0x6c, 0x6c, 0x44, 0x65, 0x62,
	0x75, 0x67, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02,
	0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x5f,
	0x73, 0x69, 0x7a, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x62, 0x6c, 0x6f, 0x63,
	0x6b, 0x53, 0x69, 0x7a, 0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x6e, 0x75, 0x6d, 0x5f, 0x62, 0x6c, 0x6f,
	0x63, 0x6b, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x6e, 0x75, 0x6d, 0x42, 0x6c,
	0x6f, 0x63, 0x6b, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x75, 0x75, 0x69, 0x64, 0x18, 0x05, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x75, 0x75, 0x69, 0x64, 0x22, 0x4b, 0x0a, 0x16, 0x4e, 0x75, 0x6c, 0x6c,
	0x44, 0x65, 0x62, 0x75, 0x67, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x31, 0x0a, 0x06, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x19, 0x2e, 0x6f, 0x70, 0x69, 0x2e, 0x73, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65,
	0x2e, 0x76, 0x31, 0x2e, 0x4e, 0x75, 0x6c, 0x6c, 0x44, 0x65, 0x62, 0x75, 0x67, 0x52, 0x06, 0x64,
	0x65, 0x76, 0x69, 0x63, 0x65, 0x22, 0x19, 0x0a, 0x17, 0x4e, 0x75, 0x6c, 0x6c, 0x44, 0x65, 0x62,
	0x75, 0x67, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x22, 0x28, 0x0a, 0x16, 0x4e, 0x75, 0x6c, 0x6c, 0x44, 0x65, 0x62, 0x75, 0x67, 0x44, 0x65, 0x6c,
	0x65, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x22, 0x19, 0x0a, 0x17, 0x4e, 0x75,
	0x6c, 0x6c, 0x44, 0x65, 0x62, 0x75, 0x67, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x4b, 0x0a, 0x16, 0x4e, 0x75, 0x6c, 0x6c, 0x44, 0x65, 0x62,
	0x75, 0x67, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x31, 0x0a, 0x06, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x19, 0x2e, 0x6f, 0x70, 0x69, 0x2e, 0x73, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x2e, 0x76, 0x31,
	0x2e, 0x4e, 0x75, 0x6c, 0x6c, 0x44, 0x65, 0x62, 0x75, 0x67, 0x52, 0x06, 0x64, 0x65, 0x76, 0x69,
	0x63, 0x65, 0x22, 0x19, 0x0a, 0x17, 0x4e, 0x75, 0x6c, 0x6c, 0x44, 0x65, 0x62, 0x75, 0x67, 0x55,
	0x70, 0x64, 0x61, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x16, 0x0a,
	0x14, 0x4e, 0x75, 0x6c, 0x6c, 0x44, 0x65, 0x62, 0x75, 0x67, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x4a, 0x0a, 0x15, 0x4e, 0x75, 0x6c, 0x6c, 0x44, 0x65, 0x62,
	0x75, 0x67, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x31,
	0x0a, 0x06, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x19,
	0x2e, 0x6f, 0x70, 0x69, 0x2e, 0x73, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x2e, 0x76, 0x31, 0x2e,
	0x4e, 0x75, 0x6c, 0x6c, 0x44, 0x65, 0x62, 0x75, 0x67, 0x52, 0x06, 0x64, 0x65, 0x76, 0x69, 0x63,
	0x65, 0x22, 0x25, 0x0a, 0x13, 0x4e, 0x75, 0x6c, 0x6c, 0x44, 0x65, 0x62, 0x75, 0x67, 0x47, 0x65,
	0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x22, 0x49, 0x0a, 0x14, 0x4e, 0x75, 0x6c, 0x6c,
	0x44, 0x65, 0x62, 0x75, 0x67, 0x47, 0x65, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x31, 0x0a, 0x06, 0x64, 0x65, 0x76, 0x69, 0x63, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x19, 0x2e, 0x6f, 0x70, 0x69, 0x2e, 0x73, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x2e, 0x76,
	0x31, 0x2e, 0x4e, 0x75, 0x6c, 0x6c, 0x44, 0x65, 0x62, 0x75, 0x67, 0x52, 0x06, 0x64, 0x65, 0x76,
	0x69, 0x63, 0x65, 0x22, 0x27, 0x0a, 0x15, 0x4e, 0x75, 0x6c, 0x6c, 0x44, 0x65, 0x62, 0x75, 0x67,
	0x53, 0x74, 0x61, 0x74, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x0e, 0x0a, 0x02,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x22, 0x3e, 0x0a, 0x16,
	0x4e, 0x75, 0x6c, 0x6c, 0x44, 0x65, 0x62, 0x75, 0x67, 0x53, 0x74, 0x61, 0x74, 0x73, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x73, 0x74, 0x61, 0x74, 0x73, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x73, 0x74, 0x61, 0x74, 0x73, 0x32, 0xe4, 0x04, 0x0a,
	0x10, 0x4e, 0x75, 0x6c, 0x6c, 0x44, 0x65, 0x62, 0x75, 0x67, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x12, 0x64, 0x0a, 0x0f, 0x4e, 0x75, 0x6c, 0x6c, 0x44, 0x65, 0x62, 0x75, 0x67, 0x43, 0x72,
	0x65, 0x61, 0x74, 0x65, 0x12, 0x26, 0x2e, 0x6f, 0x70, 0x69, 0x2e, 0x73, 0x74, 0x6f, 0x72, 0x61,
	0x67, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x4e, 0x75, 0x6c, 0x6c, 0x44, 0x65, 0x62, 0x75, 0x67, 0x43,
	0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x27, 0x2e, 0x6f,
	0x70, 0x69, 0x2e, 0x73, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x4e, 0x75,
	0x6c, 0x6c, 0x44, 0x65, 0x62, 0x75, 0x67, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x64, 0x0a, 0x0f, 0x4e, 0x75, 0x6c, 0x6c, 0x44,
	0x65, 0x62, 0x75, 0x67, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x12, 0x26, 0x2e, 0x6f, 0x70, 0x69,
	0x2e, 0x73, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x4e, 0x75, 0x6c, 0x6c,
	0x44, 0x65, 0x62, 0x75, 0x67, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x27, 0x2e, 0x6f, 0x70, 0x69, 0x2e, 0x73, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65,
	0x2e, 0x76, 0x31, 0x2e, 0x4e, 0x75, 0x6c, 0x6c, 0x44, 0x65, 0x62, 0x75, 0x67, 0x44, 0x65, 0x6c,
	0x65, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x64, 0x0a,
	0x0f, 0x4e, 0x75, 0x6c, 0x6c, 0x44, 0x65, 0x62, 0x75, 0x67, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65,
	0x12, 0x26, 0x2e, 0x6f, 0x70, 0x69, 0x2e, 0x73, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x2e, 0x76,
	0x31, 0x2e, 0x4e, 0x75, 0x6c, 0x6c, 0x44, 0x65, 0x62, 0x75, 0x67, 0x55, 0x70, 0x64, 0x61, 0x74,
	0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x27, 0x2e, 0x6f, 0x70, 0x69, 0x2e, 0x73,
	0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x4e, 0x75, 0x6c, 0x6c, 0x44, 0x65,
	0x62, 0x75, 0x67, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x22, 0x00, 0x12, 0x5e, 0x0a, 0x0d, 0x4e, 0x75, 0x6c, 0x6c, 0x44, 0x65, 0x62, 0x75, 0x67,
	0x4c, 0x69, 0x73, 0x74, 0x12, 0x24, 0x2e, 0x6f, 0x70, 0x69, 0x2e, 0x73, 0x74, 0x6f, 0x72, 0x61,
	0x67, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x4e, 0x75, 0x6c, 0x6c, 0x44, 0x65, 0x62, 0x75, 0x67, 0x4c,
	0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x25, 0x2e, 0x6f, 0x70, 0x69,
	0x2e, 0x73, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x4e, 0x75, 0x6c, 0x6c,
	0x44, 0x65, 0x62, 0x75, 0x67, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x22, 0x00, 0x12, 0x5b, 0x0a, 0x0c, 0x4e, 0x75, 0x6c, 0x6c, 0x44, 0x65, 0x62, 0x75, 0x67,
	0x47, 0x65, 0x74, 0x12, 0x23, 0x2e, 0x6f, 0x70, 0x69, 0x2e, 0x73, 0x74, 0x6f, 0x72, 0x61, 0x67,
	0x65, 0x2e, 0x76, 0x31, 0x2e, 0x4e, 0x75, 0x6c, 0x6c, 0x44, 0x65, 0x62, 0x75, 0x67, 0x47, 0x65,
	0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x24, 0x2e, 0x6f, 0x70, 0x69, 0x2e, 0x73,
	0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x4e, 0x75, 0x6c, 0x6c, 0x44, 0x65,
	0x62, 0x75, 0x67, 0x47, 0x65, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00,
	0x12, 0x61, 0x0a, 0x0e, 0x4e, 0x75, 0x6c, 0x6c, 0x44, 0x65, 0x62, 0x75, 0x67, 0x53, 0x74, 0x61,
	0x74, 0x73, 0x12, 0x25, 0x2e, 0x6f, 0x70, 0x69, 0x2e, 0x73, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65,
	0x2e, 0x76, 0x31, 0x2e, 0x4e, 0x75, 0x6c, 0x6c, 0x44, 0x65, 0x62, 0x75, 0x67, 0x53, 0x74, 0x61,
	0x74, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x26, 0x2e, 0x6f, 0x70, 0x69, 0x2e,
	0x73, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x4e, 0x75, 0x6c, 0x6c, 0x44,
	0x65, 0x62, 0x75, 0x67, 0x53, 0x74, 0x61, 0x74, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x22, 0x00, 0x42, 0x2d, 0x5a, 0x2b, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f,
	0x6d, 0x2f, 0x6f, 0x70, 0x69, 0x70, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x2f, 0x6f, 0x70, 0x69,
	0x2d, 0x61, 0x70, 0x69, 0x2f, 0x73, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x2f, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_backend_null_proto_rawDescOnce sync.Once
	file_backend_null_proto_rawDescData = file_backend_null_proto_rawDesc
)

func file_backend_null_proto_rawDescGZIP() []byte {
	file_backend_null_proto_rawDescOnce.Do(func() {
		file_backend_null_proto_rawDescData = protoimpl.X.CompressGZIP(file_backend_null_proto_rawDescData)
	})
	return file_backend_null_proto_rawDescData
}

var file_backend_null_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_backend_null_proto_goTypes = []interface{}{
	(*NullDebug)(nil),               // 0: opi.storage.v1.NullDebug
	(*NullDebugCreateRequest)(nil),  // 1: opi.storage.v1.NullDebugCreateRequest
	(*NullDebugCreateResponse)(nil), // 2: opi.storage.v1.NullDebugCreateResponse
	(*NullDebugDeleteRequest)(nil),  // 3: opi.storage.v1.NullDebugDeleteRequest
	(*NullDebugDeleteResponse)(nil), // 4: opi.storage.v1.NullDebugDeleteResponse
	(*NullDebugUpdateRequest)(nil),  // 5: opi.storage.v1.NullDebugUpdateRequest
	(*NullDebugUpdateResponse)(nil), // 6: opi.storage.v1.NullDebugUpdateResponse
	(*NullDebugListRequest)(nil),    // 7: opi.storage.v1.NullDebugListRequest
	(*NullDebugListResponse)(nil),   // 8: opi.storage.v1.NullDebugListResponse
	(*NullDebugGetRequest)(nil),     // 9: opi.storage.v1.NullDebugGetRequest
	(*NullDebugGetResponse)(nil),    // 10: opi.storage.v1.NullDebugGetResponse
	(*NullDebugStatsRequest)(nil),   // 11: opi.storage.v1.NullDebugStatsRequest
	(*NullDebugStatsResponse)(nil),  // 12: opi.storage.v1.NullDebugStatsResponse
}
var file_backend_null_proto_depIdxs = []int32{
	0,  // 0: opi.storage.v1.NullDebugCreateRequest.device:type_name -> opi.storage.v1.NullDebug
	0,  // 1: opi.storage.v1.NullDebugUpdateRequest.device:type_name -> opi.storage.v1.NullDebug
	0,  // 2: opi.storage.v1.NullDebugListResponse.device:type_name -> opi.storage.v1.NullDebug
	0,  // 3: opi.storage.v1.NullDebugGetResponse.device:type_name -> opi.storage.v1.NullDebug
	1,  // 4: opi.storage.v1.NullDebugService.NullDebugCreate:input_type -> opi.storage.v1.NullDebugCreateRequest
	3,  // 5: opi.storage.v1.NullDebugService.NullDebugDelete:input_type -> opi.storage.v1.NullDebugDeleteRequest
	5,  // 6: opi.storage.v1.NullDebugService.NullDebugUpdate:input_type -> opi.storage.v1.NullDebugUpdateRequest
	7,  // 7: opi.storage.v1.NullDebugService.NullDebugList:input_type -> opi.storage.v1.NullDebugListRequest
	9,  // 8: opi.storage.v1.NullDebugService.NullDebugGet:input_type -> opi.storage.v1.NullDebugGetRequest
	11, // 9: opi.storage.v1.NullDebugService.NullDebugStats:input_type -> opi.storage.v1.NullDebugStatsRequest
	2,  // 10: opi.storage.v1.NullDebugService.NullDebugCreate:output_type -> opi.storage.v1.NullDebugCreateResponse
	4,  // 11: opi.storage.v1.NullDebugService.NullDebugDelete:output_type -> opi.storage.v1.NullDebugDeleteResponse
	6,  // 12: opi.storage.v1.NullDebugService.NullDebugUpdate:output_type -> opi.storage.v1.NullDebugUpdateResponse
	8,  // 13: opi.storage.v1.NullDebugService.NullDebugList:output_type -> opi.storage.v1.NullDebugListResponse
	10, // 14: opi.storage.v1.NullDebugService.NullDebugGet:output_type -> opi.storage.v1.NullDebugGetResponse
	12, // 15: opi.storage.v1.NullDebugService.NullDebugStats:output_type -> opi.storage.v1.NullDebugStatsResponse
	10, // [10:16] is the sub-list for method output_type
	4,  // [4:10] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_backend_null_proto_init() }
func file_backend_null_proto_init() {
	if File_backend_null_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_backend_null_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NullDebug); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_backend_null_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NullDebugCreateRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_backend_null_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NullDebugCreateResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_backend_null_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NullDebugDeleteRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_backend_null_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NullDebugDeleteResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_backend_null_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NullDebugUpdateRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_backend_null_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NullDebugUpdateResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_backend_null_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NullDebugListRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_backend_null_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NullDebugListResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_backend_null_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NullDebugGetRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_backend_null_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NullDebugGetResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_backend_null_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NullDebugStatsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_backend_null_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NullDebugStatsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_backend_null_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_backend_null_proto_goTypes,
		DependencyIndexes: file_backend_null_proto_depIdxs,
		MessageInfos:      file_backend_null_proto_msgTypes,
	}.Build()
	File_backend_null_proto = out.File
	file_backend_null_proto_rawDesc = nil
	file_backend_null_proto_goTypes = nil
	file_backend_null_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// NullDebugServiceClient is the client API for NullDebugService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type NullDebugServiceClient interface {
	NullDebugCreate(ctx context.Context, in *NullDebugCreateRequest, opts ...grpc.CallOption) (*NullDebugCreateResponse, error)
	NullDebugDelete(ctx context.Context, in *NullDebugDeleteRequest, opts ...grpc.CallOption) (*NullDebugDeleteResponse, error)
	NullDebugUpdate(ctx context.Context, in *NullDebugUpdateRequest, opts ...grpc.CallOption) (*NullDebugUpdateResponse, error)
	NullDebugList(ctx context.Context, in *NullDebugListRequest, opts ...grpc.CallOption) (*NullDebugListResponse, error)
	NullDebugGet(ctx context.Context, in *NullDebugGetRequest, opts ...grpc.CallOption) (*NullDebugGetResponse, error)
	NullDebugStats(ctx context.Context, in *NullDebugStatsRequest, opts ...grpc.CallOption) (*NullDebugStatsResponse, error)
}

type nullDebugServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewNullDebugServiceClient(cc grpc.ClientConnInterface) NullDebugServiceClient {
	return &nullDebugServiceClient{cc}
}

func (c *nullDebugServiceClient) NullDebugCreate(ctx context.Context, in *NullDebugCreateRequest, opts ...grpc.CallOption) (*NullDebugCreateResponse, error) {
	out := new(NullDebugCreateResponse)
	err := c.cc.Invoke(ctx, "/opi.storage.v1.NullDebugService/NullDebugCreate", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nullDebugServiceClient) NullDebugDelete(ctx context.Context, in *NullDebugDeleteRequest, opts ...grpc.CallOption) (*NullDebugDeleteResponse, error) {
	out := new(NullDebugDeleteResponse)
	err := c.cc.Invoke(ctx, "/opi.storage.v1.NullDebugService/NullDebugDelete", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nullDebugServiceClient) NullDebugUpdate(ctx context.Context, in *NullDebugUpdateRequest, opts ...grpc.CallOption) (*NullDebugUpdateResponse, error) {
	out := new(NullDebugUpdateResponse)
	err := c.cc.Invoke(ctx, "/opi.storage.v1.NullDebugService/NullDebugUpdate", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nullDebugServiceClient) NullDebugList(ctx context.Context, in *NullDebugListRequest, opts ...grpc.CallOption) (*NullDebugListResponse, error) {
	out := new(NullDebugListResponse)
	err := c.cc.Invoke(ctx, "/opi.storage.v1.NullDebugService/NullDebugList", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nullDebugServiceClient) NullDebugGet(ctx context.Context, in *NullDebugGetRequest, opts ...grpc.CallOption) (*NullDebugGetResponse, error) {
	out := new(NullDebugGetResponse)
	err := c.cc.Invoke(ctx, "/opi.storage.v1.NullDebugService/NullDebugGet", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *nullDebugServiceClient) NullDebugStats(ctx context.Context, in *NullDebugStatsRequest, opts ...grpc.CallOption) (*NullDebugStatsResponse, error) {
	out := new(NullDebugStatsResponse)
	err := c.cc.Invoke(ctx, "/opi.storage.v1.NullDebugService/NullDebugStats", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// NullDebugServiceServer is the server API for NullDebugService service.
type NullDebugServiceServer interface {
	NullDebugCreate(context.Context, *NullDebugCreateRequest) (*NullDebugCreateResponse, error)
	NullDebugDelete(context.Context, *NullDebugDeleteRequest) (*NullDebugDeleteResponse, error)
	NullDebugUpdate(context.Context, *NullDebugUpdateRequest) (*NullDebugUpdateResponse, error)
	NullDebugList(context.Context, *NullDebugListRequest) (*NullDebugListResponse, error)
	NullDebugGet(context.Context, *NullDebugGetRequest) (*NullDebugGetResponse, error)
	NullDebugStats(context.Context, *NullDebugStatsRequest) (*NullDebugStatsResponse, error)
}

// UnimplementedNullDebugServiceServer can be embedded to have forward compatible implementations.
type UnimplementedNullDebugServiceServer struct {
}

func (*UnimplementedNullDebugServiceServer) NullDebugCreate(context.Context, *NullDebugCreateRequest) (*NullDebugCreateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method NullDebugCreate not implemented")
}
func (*UnimplementedNullDebugServiceServer) NullDebugDelete(context.Context, *NullDebugDeleteRequest) (*NullDebugDeleteResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method NullDebugDelete not implemented")
}
func (*UnimplementedNullDebugServiceServer) NullDebugUpdate(context.Context, *NullDebugUpdateRequest) (*NullDebugUpdateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method NullDebugUpdate not implemented")
}
func (*UnimplementedNullDebugServiceServer) NullDebugList(context.Context, *NullDebugListRequest) (*NullDebugListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method NullDebugList not implemented")
}
func (*UnimplementedNullDebugServiceServer) NullDebugGet(context.Context, *NullDebugGetRequest) (*NullDebugGetResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method NullDebugGet not implemented")
}
func (*UnimplementedNullDebugServiceServer) NullDebugStats(context.Context, *NullDebugStatsRequest) (*NullDebugStatsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method NullDebugStats not implemented")
}

func RegisterNullDebugServiceServer(s *grpc.Server, srv NullDebugServiceServer) {
	s.RegisterService(&_NullDebugService_serviceDesc, srv)
}

func _NullDebugService_NullDebugCreate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NullDebugCreateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NullDebugServiceServer).NullDebugCreate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/opi.storage.v1.NullDebugService/NullDebugCreate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NullDebugServiceServer).NullDebugCreate(ctx, req.(*NullDebugCreateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NullDebugService_NullDebugDelete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NullDebugDeleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NullDebugServiceServer).NullDebugDelete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/opi.storage.v1.NullDebugService/NullDebugDelete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NullDebugServiceServer).NullDebugDelete(ctx, req.(*NullDebugDeleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NullDebugService_NullDebugUpdate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NullDebugUpdateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NullDebugServiceServer).NullDebugUpdate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/opi.storage.v1.NullDebugService/NullDebugUpdate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NullDebugServiceServer).NullDebugUpdate(ctx, req.(*NullDebugUpdateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NullDebugService_NullDebugList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NullDebugListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NullDebugServiceServer).NullDebugList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/opi.storage.v1.NullDebugService/NullDebugList",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NullDebugServiceServer).NullDebugList(ctx, req.(*NullDebugListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NullDebugService_NullDebugGet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NullDebugGetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NullDebugServiceServer).NullDebugGet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/opi.storage.v1.NullDebugService/NullDebugGet",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NullDebugServiceServer).NullDebugGet(ctx, req.(*NullDebugGetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _NullDebugService_NullDebugStats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NullDebugStatsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NullDebugServiceServer).NullDebugStats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/opi.storage.v1.NullDebugService/NullDebugStats",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NullDebugServiceServer).NullDebugStats(ctx, req.(*NullDebugStatsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _NullDebugService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "opi.storage.v1.NullDebugService",
	HandlerType: (*NullDebugServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "NullDebugCreate",
			Handler:    _NullDebugService_NullDebugCreate_Handler,
		},
		{
			MethodName: "NullDebugDelete",
			Handler:    _NullDebugService_NullDebugDelete_Handler,
		},
		{
			MethodName: "NullDebugUpdate",
			Handler:    _NullDebugService_NullDebugUpdate_Handler,
		},
		{
			MethodName: "NullDebugList",
			Handler:    _NullDebugService_NullDebugList_Handler,
		},
		{
			MethodName: "NullDebugGet",
			Handler:    _NullDebugService_NullDebugGet_Handler,
		},
		{
			MethodName: "NullDebugStats",
			Handler:    _NullDebugService_NullDebugStats_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "backend-null.proto",
}
