// SPDX-License-Identifier: Apache-2.0
// Copyright (c) 2022 Dell Inc, or its subsidiaries.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.19.4
// source: frontend-virtio-blk.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type VirtioBlk struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id           int64                `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name         string               `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	PcieId       *NvmeControllerPciId `protobuf:"bytes,3,opt,name=pcie_id,json=pcieId,proto3" json:"pcie_id,omitempty"`
	Bdev         string               `protobuf:"bytes,4,opt,name=bdev,proto3" json:"bdev,omitempty"`
	MaxIoQps     int64                `protobuf:"varint,5,opt,name=max_io_qps,json=maxIoQps,proto3" json:"max_io_qps,omitempty"`
	SerialNumber string               `protobuf:"bytes,6,opt,name=serial_number,json=serialNumber,proto3" json:"serial_number,omitempty"`
}

func (x *VirtioBlk) Reset() {
	*x = VirtioBlk{}
	if protoimpl.UnsafeEnabled {
		mi := &file_frontend_virtio_blk_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VirtioBlk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VirtioBlk) ProtoMessage() {}

func (x *VirtioBlk) ProtoReflect() protoreflect.Message {
	mi := &file_frontend_virtio_blk_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VirtioBlk.ProtoReflect.Descriptor instead.
func (*VirtioBlk) Descriptor() ([]byte, []int) {
	return file_frontend_virtio_blk_proto_rawDescGZIP(), []int{0}
}

func (x *VirtioBlk) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *VirtioBlk) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *VirtioBlk) GetPcieId() *NvmeControllerPciId {
	if x != nil {
		return x.PcieId
	}
	return nil
}

func (x *VirtioBlk) GetBdev() string {
	if x != nil {
		return x.Bdev
	}
	return ""
}

func (x *VirtioBlk) GetMaxIoQps() int64 {
	if x != nil {
		return x.MaxIoQps
	}
	return 0
}

func (x *VirtioBlk) GetSerialNumber() string {
	if x != nil {
		return x.SerialNumber
	}
	return ""
}

type VirtioBlkCreateRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Controller *VirtioBlk `protobuf:"bytes,1,opt,name=controller,proto3" json:"controller,omitempty"`
}

func (x *VirtioBlkCreateRequest) Reset() {
	*x = VirtioBlkCreateRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_frontend_virtio_blk_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VirtioBlkCreateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VirtioBlkCreateRequest) ProtoMessage() {}

func (x *VirtioBlkCreateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_frontend_virtio_blk_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VirtioBlkCreateRequest.ProtoReflect.Descriptor instead.
func (*VirtioBlkCreateRequest) Descriptor() ([]byte, []int) {
	return file_frontend_virtio_blk_proto_rawDescGZIP(), []int{1}
}

func (x *VirtioBlkCreateRequest) GetController() *VirtioBlk {
	if x != nil {
		return x.Controller
	}
	return nil
}

type VirtioBlkCreateResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *VirtioBlkCreateResponse) Reset() {
	*x = VirtioBlkCreateResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_frontend_virtio_blk_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VirtioBlkCreateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VirtioBlkCreateResponse) ProtoMessage() {}

func (x *VirtioBlkCreateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_frontend_virtio_blk_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VirtioBlkCreateResponse.ProtoReflect.Descriptor instead.
func (*VirtioBlkCreateResponse) Descriptor() ([]byte, []int) {
	return file_frontend_virtio_blk_proto_rawDescGZIP(), []int{2}
}

type VirtioBlkDeleteRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ControllerId int64 `protobuf:"varint,1,opt,name=controller_id,json=controllerId,proto3" json:"controller_id,omitempty"`
}

func (x *VirtioBlkDeleteRequest) Reset() {
	*x = VirtioBlkDeleteRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_frontend_virtio_blk_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VirtioBlkDeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VirtioBlkDeleteRequest) ProtoMessage() {}

func (x *VirtioBlkDeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_frontend_virtio_blk_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VirtioBlkDeleteRequest.ProtoReflect.Descriptor instead.
func (*VirtioBlkDeleteRequest) Descriptor() ([]byte, []int) {
	return file_frontend_virtio_blk_proto_rawDescGZIP(), []int{3}
}

func (x *VirtioBlkDeleteRequest) GetControllerId() int64 {
	if x != nil {
		return x.ControllerId
	}
	return 0
}

type VirtioBlkDeleteResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *VirtioBlkDeleteResponse) Reset() {
	*x = VirtioBlkDeleteResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_frontend_virtio_blk_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VirtioBlkDeleteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VirtioBlkDeleteResponse) ProtoMessage() {}

func (x *VirtioBlkDeleteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_frontend_virtio_blk_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VirtioBlkDeleteResponse.ProtoReflect.Descriptor instead.
func (*VirtioBlkDeleteResponse) Descriptor() ([]byte, []int) {
	return file_frontend_virtio_blk_proto_rawDescGZIP(), []int{4}
}

type VirtioBlkUpdateRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Controller *VirtioBlk `protobuf:"bytes,1,opt,name=controller,proto3" json:"controller,omitempty"`
}

func (x *VirtioBlkUpdateRequest) Reset() {
	*x = VirtioBlkUpdateRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_frontend_virtio_blk_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VirtioBlkUpdateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VirtioBlkUpdateRequest) ProtoMessage() {}

func (x *VirtioBlkUpdateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_frontend_virtio_blk_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VirtioBlkUpdateRequest.ProtoReflect.Descriptor instead.
func (*VirtioBlkUpdateRequest) Descriptor() ([]byte, []int) {
	return file_frontend_virtio_blk_proto_rawDescGZIP(), []int{5}
}

func (x *VirtioBlkUpdateRequest) GetController() *VirtioBlk {
	if x != nil {
		return x.Controller
	}
	return nil
}

type VirtioBlkUpdateResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *VirtioBlkUpdateResponse) Reset() {
	*x = VirtioBlkUpdateResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_frontend_virtio_blk_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VirtioBlkUpdateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VirtioBlkUpdateResponse) ProtoMessage() {}

func (x *VirtioBlkUpdateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_frontend_virtio_blk_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VirtioBlkUpdateResponse.ProtoReflect.Descriptor instead.
func (*VirtioBlkUpdateResponse) Descriptor() ([]byte, []int) {
	return file_frontend_virtio_blk_proto_rawDescGZIP(), []int{6}
}

type VirtioBlkListRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SubsystemId int64 `protobuf:"varint,1,opt,name=subsystem_id,json=subsystemId,proto3" json:"subsystem_id,omitempty"`
}

func (x *VirtioBlkListRequest) Reset() {
	*x = VirtioBlkListRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_frontend_virtio_blk_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VirtioBlkListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VirtioBlkListRequest) ProtoMessage() {}

func (x *VirtioBlkListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_frontend_virtio_blk_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VirtioBlkListRequest.ProtoReflect.Descriptor instead.
func (*VirtioBlkListRequest) Descriptor() ([]byte, []int) {
	return file_frontend_virtio_blk_proto_rawDescGZIP(), []int{7}
}

func (x *VirtioBlkListRequest) GetSubsystemId() int64 {
	if x != nil {
		return x.SubsystemId
	}
	return 0
}

type VirtioBlkListResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *VirtioBlkListResponse) Reset() {
	*x = VirtioBlkListResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_frontend_virtio_blk_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VirtioBlkListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VirtioBlkListResponse) ProtoMessage() {}

func (x *VirtioBlkListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_frontend_virtio_blk_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VirtioBlkListResponse.ProtoReflect.Descriptor instead.
func (*VirtioBlkListResponse) Descriptor() ([]byte, []int) {
	return file_frontend_virtio_blk_proto_rawDescGZIP(), []int{8}
}

type VirtioBlkGetRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ControllerId int64 `protobuf:"varint,1,opt,name=controller_id,json=controllerId,proto3" json:"controller_id,omitempty"`
}

func (x *VirtioBlkGetRequest) Reset() {
	*x = VirtioBlkGetRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_frontend_virtio_blk_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VirtioBlkGetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VirtioBlkGetRequest) ProtoMessage() {}

func (x *VirtioBlkGetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_frontend_virtio_blk_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VirtioBlkGetRequest.ProtoReflect.Descriptor instead.
func (*VirtioBlkGetRequest) Descriptor() ([]byte, []int) {
	return file_frontend_virtio_blk_proto_rawDescGZIP(), []int{9}
}

func (x *VirtioBlkGetRequest) GetControllerId() int64 {
	if x != nil {
		return x.ControllerId
	}
	return 0
}

type VirtioBlkGetResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Controller *VirtioBlk `protobuf:"bytes,1,opt,name=controller,proto3" json:"controller,omitempty"`
}

func (x *VirtioBlkGetResponse) Reset() {
	*x = VirtioBlkGetResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_frontend_virtio_blk_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VirtioBlkGetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VirtioBlkGetResponse) ProtoMessage() {}

func (x *VirtioBlkGetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_frontend_virtio_blk_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VirtioBlkGetResponse.ProtoReflect.Descriptor instead.
func (*VirtioBlkGetResponse) Descriptor() ([]byte, []int) {
	return file_frontend_virtio_blk_proto_rawDescGZIP(), []int{10}
}

func (x *VirtioBlkGetResponse) GetController() *VirtioBlk {
	if x != nil {
		return x.Controller
	}
	return nil
}

type VirtioBlkStatsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ControllerId int64 `protobuf:"varint,1,opt,name=controller_id,json=controllerId,proto3" json:"controller_id,omitempty"`
}

func (x *VirtioBlkStatsRequest) Reset() {
	*x = VirtioBlkStatsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_frontend_virtio_blk_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VirtioBlkStatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VirtioBlkStatsRequest) ProtoMessage() {}

func (x *VirtioBlkStatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_frontend_virtio_blk_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VirtioBlkStatsRequest.ProtoReflect.Descriptor instead.
func (*VirtioBlkStatsRequest) Descriptor() ([]byte, []int) {
	return file_frontend_virtio_blk_proto_rawDescGZIP(), []int{11}
}

func (x *VirtioBlkStatsRequest) GetControllerId() int64 {
	if x != nil {
		return x.ControllerId
	}
	return 0
}

type VirtioBlkStatsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id    int64  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Stats string `protobuf:"bytes,2,opt,name=stats,proto3" json:"stats,omitempty"`
}

func (x *VirtioBlkStatsResponse) Reset() {
	*x = VirtioBlkStatsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_frontend_virtio_blk_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VirtioBlkStatsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VirtioBlkStatsResponse) ProtoMessage() {}

func (x *VirtioBlkStatsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_frontend_virtio_blk_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VirtioBlkStatsResponse.ProtoReflect.Descriptor instead.
func (*VirtioBlkStatsResponse) Descriptor() ([]byte, []int) {
	return file_frontend_virtio_blk_proto_rawDescGZIP(), []int{12}
}

func (x *VirtioBlkStatsResponse) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *VirtioBlkStatsResponse) GetStats() string {
	if x != nil {
		return x.Stats
	}
	return ""
}

var File_frontend_virtio_blk_proto protoreflect.FileDescriptor

var file_frontend_virtio_blk_proto_rawDesc = []byte{
	0x0a, 0x19, 0x66, 0x72, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x64, 0x2d, 0x76, 0x69, 0x72, 0x74, 0x69,
	0x6f, 0x2d, 0x62, 0x6c, 0x6b, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0e, 0x6f, 0x70, 0x69,
	0x2e, 0x73, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x2e, 0x76, 0x31, 0x1a, 0x0c, 0x63, 0x6f, 0x6d,
	0x6d, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xc4, 0x01, 0x0a, 0x09, 0x56, 0x69,
	0x72, 0x74, 0x69, 0x6f, 0x42, 0x6c, 0x6b, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x3c, 0x0a, 0x07, 0x70,
	0x63, 0x69, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x23, 0x2e, 0x6f,
	0x70, 0x69, 0x2e, 0x73, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x4e, 0x76,
	0x6d, 0x65, 0x43, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x6c, 0x65, 0x72, 0x50, 0x63, 0x69, 0x49,
	0x64, 0x52, 0x06, 0x70, 0x63, 0x69, 0x65, 0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x62, 0x64, 0x65,
	0x76, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x62, 0x64, 0x65, 0x76, 0x12, 0x1c, 0x0a,
	0x0a, 0x6d, 0x61, 0x78, 0x5f, 0x69, 0x6f, 0x5f, 0x71, 0x70, 0x73, 0x18, 0x05, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x08, 0x6d, 0x61, 0x78, 0x49, 0x6f, 0x51, 0x70, 0x73, 0x12, 0x23, 0x0a, 0x0d, 0x73,
	0x65, 0x72, 0x69, 0x61, 0x6c, 0x5f, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x18, 0x06, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0c, 0x73, 0x65, 0x72, 0x69, 0x61, 0x6c, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72,
	0x22, 0x53, 0x0a, 0x16, 0x56, 0x69, 0x72, 0x74, 0x69, 0x6f, 0x42, 0x6c, 0x6b, 0x43, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x39, 0x0a, 0x0a, 0x63, 0x6f,
	0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x6c, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x19,
	0x2e, 0x6f, 0x70, 0x69, 0x2e, 0x73, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x2e, 0x76, 0x31, 0x2e,
	0x56, 0x69, 0x72, 0x74, 0x69, 0x6f, 0x42, 0x6c, 0x6b, 0x52, 0x0a, 0x63, 0x6f, 0x6e, 0x74, 0x72,
	0x6f, 0x6c, 0x6c, 0x65, 0x72, 0x22, 0x19, 0x0a, 0x17, 0x56, 0x69, 0x72, 0x74, 0x69, 0x6f, 0x42,
	0x6c, 0x6b, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x22, 0x3d, 0x0a, 0x16, 0x56, 0x69, 0x72, 0x74, 0x69, 0x6f, 0x42, 0x6c, 0x6b, 0x44, 0x65, 0x6c,
	0x65, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x23, 0x0a, 0x0d, 0x63, 0x6f,
	0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x6c, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x0c, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x6c, 0x65, 0x72, 0x49, 0x64, 0x22,
	0x19, 0x0a, 0x17, 0x56, 0x69, 0x72, 0x74, 0x69, 0x6f, 0x42, 0x6c, 0x6b, 0x44, 0x65, 0x6c, 0x65,
	0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x53, 0x0a, 0x16, 0x56, 0x69,
	0x72, 0x74, 0x69, 0x6f, 0x42, 0x6c, 0x6b, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x39, 0x0a, 0x0a, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x6c,
	0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x6f, 0x70, 0x69, 0x2e, 0x73,
	0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x56, 0x69, 0x72, 0x74, 0x69, 0x6f,
	0x42, 0x6c, 0x6b, 0x52, 0x0a, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x6c, 0x65, 0x72, 0x22,
	0x19, 0x0a, 0x17, 0x56, 0x69, 0x72, 0x74, 0x69, 0x6f, 0x42, 0x6c, 0x6b, 0x55, 0x70, 0x64, 0x61,
	0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x39, 0x0a, 0x14, 0x56, 0x69,
	0x72, 0x74, 0x69, 0x6f, 0x42, 0x6c, 0x6b, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x21, 0x0a, 0x0c, 0x73, 0x75, 0x62, 0x73, 0x79, 0x73, 0x74, 0x65, 0x6d, 0x5f,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0b, 0x73, 0x75, 0x62, 0x73, 0x79, 0x73,
	0x74, 0x65, 0x6d, 0x49, 0x64, 0x22, 0x17, 0x0a, 0x15, 0x56, 0x69, 0x72, 0x74, 0x69, 0x6f, 0x42,
	0x6c, 0x6b, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x3a,
	0x0a, 0x13, 0x56, 0x69, 0x72, 0x74, 0x69, 0x6f, 0x42, 0x6c, 0x6b, 0x47, 0x65, 0x74, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x23, 0x0a, 0x0d, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c,
	0x6c, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0c, 0x63, 0x6f,
	0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x6c, 0x65, 0x72, 0x49, 0x64, 0x22, 0x51, 0x0a, 0x14, 0x56, 0x69,
	0x72, 0x74, 0x69, 0x6f, 0x42, 0x6c, 0x6b, 0x47, 0x65, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x39, 0x0a, 0x0a, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x6c, 0x65, 0x72,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x6f, 0x70, 0x69, 0x2e, 0x73, 0x74, 0x6f,
	0x72, 0x61, 0x67, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x56, 0x69, 0x72, 0x74, 0x69, 0x6f, 0x42, 0x6c,
	0x6b, 0x52, 0x0a, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x6c, 0x65, 0x72, 0x22, 0x3c, 0x0a,
	0x15, 0x56, 0x69, 0x72, 0x74, 0x69, 0x6f, 0x42, 0x6c, 0x6b, 0x53, 0x74, 0x61, 0x74, 0x73, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x23, 0x0a, 0x0d, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x6f,
	0x6c, 0x6c, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0c, 0x63,
	0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x6c, 0x65, 0x72, 0x49, 0x64, 0x22, 0x3e, 0x0a, 0x16, 0x56,
	0x69, 0x72, 0x74, 0x69, 0x6f, 0x42, 0x6c, 0x6b, 0x53, 0x74, 0x61, 0x74, 0x73, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x02, 0x69, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x73, 0x74, 0x61, 0x74, 0x73, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x73, 0x74, 0x61, 0x74, 0x73, 0x32, 0xe4, 0x04, 0x0a, 0x10,
	0x56, 0x69, 0x72, 0x74, 0x69, 0x6f, 0x42, 0x6c, 0x6b, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x12, 0x64, 0x0a, 0x0f, 0x56, 0x69, 0x72, 0x74, 0x69, 0x6f, 0x42, 0x6c, 0x6b, 0x43, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x12, 0x26, 0x2e, 0x6f, 0x70, 0x69, 0x2e, 0x73, 0x74, 0x6f, 0x72, 0x61, 0x67,
	0x65, 0x2e, 0x76, 0x31, 0x2e, 0x56, 0x69, 0x72, 0x74, 0x69, 0x6f, 0x42, 0x6c, 0x6b, 0x43, 0x72,
	0x65, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x27, 0x2e, 0x6f, 0x70,
	0x69, 0x2e, 0x73, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x56, 0x69, 0x72,
	0x74, 0x69, 0x6f, 0x42, 0x6c, 0x6b, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x64, 0x0a, 0x0f, 0x56, 0x69, 0x72, 0x74, 0x69, 0x6f,
	0x42, 0x6c, 0x6b, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x12, 0x26, 0x2e, 0x6f, 0x70, 0x69, 0x2e,
	0x73, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x56, 0x69, 0x72, 0x74, 0x69,
	0x6f, 0x42, 0x6c, 0x6b, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x27, 0x2e, 0x6f, 0x70, 0x69, 0x2e, 0x73, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x2e,
	0x76, 0x31, 0x2e, 0x56, 0x69, 0x72, 0x74, 0x69, 0x6f, 0x42, 0x6c, 0x6b, 0x44, 0x65, 0x6c, 0x65,
	0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x64, 0x0a, 0x0f,
	0x56, 0x69, 0x72, 0x74, 0x69, 0x6f, 0x42, 0x6c, 0x6b, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x12,
	0x26, 0x2e, 0x6f, 0x70, 0x69, 0x2e, 0x73, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x2e, 0x76, 0x31,
	0x2e, 0x56, 0x69, 0x72, 0x74, 0x69, 0x6f, 0x42, 0x6c, 0x6b, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x27, 0x2e, 0x6f, 0x70, 0x69, 0x2e, 0x73, 0x74,
	0x6f, 0x72, 0x61, 0x67, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x56, 0x69, 0x72, 0x74, 0x69, 0x6f, 0x42,
	0x6c, 0x6b, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x22, 0x00, 0x12, 0x5e, 0x0a, 0x0d, 0x56, 0x69, 0x72, 0x74, 0x69, 0x6f, 0x42, 0x6c, 0x6b, 0x4c,
	0x69, 0x73, 0x74, 0x12, 0x24, 0x2e, 0x6f, 0x70, 0x69, 0x2e, 0x73, 0x74, 0x6f, 0x72, 0x61, 0x67,
	0x65, 0x2e, 0x76, 0x31, 0x2e, 0x56, 0x69, 0x72, 0x74, 0x69, 0x6f, 0x42, 0x6c, 0x6b, 0x4c, 0x69,
	0x73, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x25, 0x2e, 0x6f, 0x70, 0x69, 0x2e,
	0x73, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x56, 0x69, 0x72, 0x74, 0x69,
	0x6f, 0x42, 0x6c, 0x6b, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x22, 0x00, 0x12, 0x5b, 0x0a, 0x0c, 0x56, 0x69, 0x72, 0x74, 0x69, 0x6f, 0x42, 0x6c, 0x6b, 0x47,
	0x65, 0x74, 0x12, 0x23, 0x2e, 0x6f, 0x70, 0x69, 0x2e, 0x73, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65,
	0x2e, 0x76, 0x31, 0x2e, 0x56, 0x69, 0x72, 0x74, 0x69, 0x6f, 0x42, 0x6c, 0x6b, 0x47, 0x65, 0x74,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x24, 0x2e, 0x6f, 0x70, 0x69, 0x2e, 0x73, 0x74,
	0x6f, 0x72, 0x61, 0x67, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x56, 0x69, 0x72, 0x74, 0x69, 0x6f, 0x42,
	0x6c, 0x6b, 0x47, 0x65, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12,
	0x61, 0x0a, 0x0e, 0x56, 0x69, 0x72, 0x74, 0x69, 0x6f, 0x42, 0x6c, 0x6b, 0x53, 0x74, 0x61, 0x74,
	0x73, 0x12, 0x25, 0x2e, 0x6f, 0x70, 0x69, 0x2e, 0x73, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x2e,
	0x76, 0x31, 0x2e, 0x56, 0x69, 0x72, 0x74, 0x69, 0x6f, 0x42, 0x6c, 0x6b, 0x53, 0x74, 0x61, 0x74,
	0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x26, 0x2e, 0x6f, 0x70, 0x69, 0x2e, 0x73,
	0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x56, 0x69, 0x72, 0x74, 0x69, 0x6f,
	0x42, 0x6c, 0x6b, 0x53, 0x74, 0x61, 0x74, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x22, 0x00, 0x42, 0x2d, 0x5a, 0x2b, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d,
	0x2f, 0x6f, 0x70, 0x69, 0x70, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x2f, 0x6f, 0x70, 0x69, 0x2d,
	0x61, 0x70, 0x69, 0x2f, 0x73, 0x74, 0x6f, 0x72, 0x61, 0x67, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_frontend_virtio_blk_proto_rawDescOnce sync.Once
	file_frontend_virtio_blk_proto_rawDescData = file_frontend_virtio_blk_proto_rawDesc
)

func file_frontend_virtio_blk_proto_rawDescGZIP() []byte {
	file_frontend_virtio_blk_proto_rawDescOnce.Do(func() {
		file_frontend_virtio_blk_proto_rawDescData = protoimpl.X.CompressGZIP(file_frontend_virtio_blk_proto_rawDescData)
	})
	return file_frontend_virtio_blk_proto_rawDescData
}

var file_frontend_virtio_blk_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_frontend_virtio_blk_proto_goTypes = []interface{}{
	(*VirtioBlk)(nil),               // 0: opi.storage.v1.VirtioBlk
	(*VirtioBlkCreateRequest)(nil),  // 1: opi.storage.v1.VirtioBlkCreateRequest
	(*VirtioBlkCreateResponse)(nil), // 2: opi.storage.v1.VirtioBlkCreateResponse
	(*VirtioBlkDeleteRequest)(nil),  // 3: opi.storage.v1.VirtioBlkDeleteRequest
	(*VirtioBlkDeleteResponse)(nil), // 4: opi.storage.v1.VirtioBlkDeleteResponse
	(*VirtioBlkUpdateRequest)(nil),  // 5: opi.storage.v1.VirtioBlkUpdateRequest
	(*VirtioBlkUpdateResponse)(nil), // 6: opi.storage.v1.VirtioBlkUpdateResponse
	(*VirtioBlkListRequest)(nil),    // 7: opi.storage.v1.VirtioBlkListRequest
	(*VirtioBlkListResponse)(nil),   // 8: opi.storage.v1.VirtioBlkListResponse
	(*VirtioBlkGetRequest)(nil),     // 9: opi.storage.v1.VirtioBlkGetRequest
	(*VirtioBlkGetResponse)(nil),    // 10: opi.storage.v1.VirtioBlkGetResponse
	(*VirtioBlkStatsRequest)(nil),   // 11: opi.storage.v1.VirtioBlkStatsRequest
	(*VirtioBlkStatsResponse)(nil),  // 12: opi.storage.v1.VirtioBlkStatsResponse
	(*NvmeControllerPciId)(nil),     // 13: opi.storage.v1.NvmeControllerPciId
}
var file_frontend_virtio_blk_proto_depIdxs = []int32{
	13, // 0: opi.storage.v1.VirtioBlk.pcie_id:type_name -> opi.storage.v1.NvmeControllerPciId
	0,  // 1: opi.storage.v1.VirtioBlkCreateRequest.controller:type_name -> opi.storage.v1.VirtioBlk
	0,  // 2: opi.storage.v1.VirtioBlkUpdateRequest.controller:type_name -> opi.storage.v1.VirtioBlk
	0,  // 3: opi.storage.v1.VirtioBlkGetResponse.controller:type_name -> opi.storage.v1.VirtioBlk
	1,  // 4: opi.storage.v1.VirtioBlkService.VirtioBlkCreate:input_type -> opi.storage.v1.VirtioBlkCreateRequest
	3,  // 5: opi.storage.v1.VirtioBlkService.VirtioBlkDelete:input_type -> opi.storage.v1.VirtioBlkDeleteRequest
	5,  // 6: opi.storage.v1.VirtioBlkService.VirtioBlkUpdate:input_type -> opi.storage.v1.VirtioBlkUpdateRequest
	7,  // 7: opi.storage.v1.VirtioBlkService.VirtioBlkList:input_type -> opi.storage.v1.VirtioBlkListRequest
	9,  // 8: opi.storage.v1.VirtioBlkService.VirtioBlkGet:input_type -> opi.storage.v1.VirtioBlkGetRequest
	11, // 9: opi.storage.v1.VirtioBlkService.VirtioBlkStats:input_type -> opi.storage.v1.VirtioBlkStatsRequest
	2,  // 10: opi.storage.v1.VirtioBlkService.VirtioBlkCreate:output_type -> opi.storage.v1.VirtioBlkCreateResponse
	4,  // 11: opi.storage.v1.VirtioBlkService.VirtioBlkDelete:output_type -> opi.storage.v1.VirtioBlkDeleteResponse
	6,  // 12: opi.storage.v1.VirtioBlkService.VirtioBlkUpdate:output_type -> opi.storage.v1.VirtioBlkUpdateResponse
	8,  // 13: opi.storage.v1.VirtioBlkService.VirtioBlkList:output_type -> opi.storage.v1.VirtioBlkListResponse
	10, // 14: opi.storage.v1.VirtioBlkService.VirtioBlkGet:output_type -> opi.storage.v1.VirtioBlkGetResponse
	12, // 15: opi.storage.v1.VirtioBlkService.VirtioBlkStats:output_type -> opi.storage.v1.VirtioBlkStatsResponse
	10, // [10:16] is the sub-list for method output_type
	4,  // [4:10] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_frontend_virtio_blk_proto_init() }
func file_frontend_virtio_blk_proto_init() {
	if File_frontend_virtio_blk_proto != nil {
		return
	}
	file_common_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_frontend_virtio_blk_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VirtioBlk); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_frontend_virtio_blk_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VirtioBlkCreateRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_frontend_virtio_blk_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VirtioBlkCreateResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_frontend_virtio_blk_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VirtioBlkDeleteRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_frontend_virtio_blk_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VirtioBlkDeleteResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_frontend_virtio_blk_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VirtioBlkUpdateRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_frontend_virtio_blk_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VirtioBlkUpdateResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_frontend_virtio_blk_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VirtioBlkListRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_frontend_virtio_blk_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VirtioBlkListResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_frontend_virtio_blk_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VirtioBlkGetRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_frontend_virtio_blk_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VirtioBlkGetResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_frontend_virtio_blk_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VirtioBlkStatsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_frontend_virtio_blk_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VirtioBlkStatsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_frontend_virtio_blk_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_frontend_virtio_blk_proto_goTypes,
		DependencyIndexes: file_frontend_virtio_blk_proto_depIdxs,
		MessageInfos:      file_frontend_virtio_blk_proto_msgTypes,
	}.Build()
	File_frontend_virtio_blk_proto = out.File
	file_frontend_virtio_blk_proto_rawDesc = nil
	file_frontend_virtio_blk_proto_goTypes = nil
	file_frontend_virtio_blk_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// VirtioBlkServiceClient is the client API for VirtioBlkService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type VirtioBlkServiceClient interface {
	VirtioBlkCreate(ctx context.Context, in *VirtioBlkCreateRequest, opts ...grpc.CallOption) (*VirtioBlkCreateResponse, error)
	VirtioBlkDelete(ctx context.Context, in *VirtioBlkDeleteRequest, opts ...grpc.CallOption) (*VirtioBlkDeleteResponse, error)
	VirtioBlkUpdate(ctx context.Context, in *VirtioBlkUpdateRequest, opts ...grpc.CallOption) (*VirtioBlkUpdateResponse, error)
	VirtioBlkList(ctx context.Context, in *VirtioBlkListRequest, opts ...grpc.CallOption) (*VirtioBlkListResponse, error)
	VirtioBlkGet(ctx context.Context, in *VirtioBlkGetRequest, opts ...grpc.CallOption) (*VirtioBlkGetResponse, error)
	VirtioBlkStats(ctx context.Context, in *VirtioBlkStatsRequest, opts ...grpc.CallOption) (*VirtioBlkStatsResponse, error)
}

type virtioBlkServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewVirtioBlkServiceClient(cc grpc.ClientConnInterface) VirtioBlkServiceClient {
	return &virtioBlkServiceClient{cc}
}

func (c *virtioBlkServiceClient) VirtioBlkCreate(ctx context.Context, in *VirtioBlkCreateRequest, opts ...grpc.CallOption) (*VirtioBlkCreateResponse, error) {
	out := new(VirtioBlkCreateResponse)
	err := c.cc.Invoke(ctx, "/opi.storage.v1.VirtioBlkService/VirtioBlkCreate", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *virtioBlkServiceClient) VirtioBlkDelete(ctx context.Context, in *VirtioBlkDeleteRequest, opts ...grpc.CallOption) (*VirtioBlkDeleteResponse, error) {
	out := new(VirtioBlkDeleteResponse)
	err := c.cc.Invoke(ctx, "/opi.storage.v1.VirtioBlkService/VirtioBlkDelete", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *virtioBlkServiceClient) VirtioBlkUpdate(ctx context.Context, in *VirtioBlkUpdateRequest, opts ...grpc.CallOption) (*VirtioBlkUpdateResponse, error) {
	out := new(VirtioBlkUpdateResponse)
	err := c.cc.Invoke(ctx, "/opi.storage.v1.VirtioBlkService/VirtioBlkUpdate", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *virtioBlkServiceClient) VirtioBlkList(ctx context.Context, in *VirtioBlkListRequest, opts ...grpc.CallOption) (*VirtioBlkListResponse, error) {
	out := new(VirtioBlkListResponse)
	err := c.cc.Invoke(ctx, "/opi.storage.v1.VirtioBlkService/VirtioBlkList", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *virtioBlkServiceClient) VirtioBlkGet(ctx context.Context, in *VirtioBlkGetRequest, opts ...grpc.CallOption) (*VirtioBlkGetResponse, error) {
	out := new(VirtioBlkGetResponse)
	err := c.cc.Invoke(ctx, "/opi.storage.v1.VirtioBlkService/VirtioBlkGet", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *virtioBlkServiceClient) VirtioBlkStats(ctx context.Context, in *VirtioBlkStatsRequest, opts ...grpc.CallOption) (*VirtioBlkStatsResponse, error) {
	out := new(VirtioBlkStatsResponse)
	err := c.cc.Invoke(ctx, "/opi.storage.v1.VirtioBlkService/VirtioBlkStats", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// VirtioBlkServiceServer is the server API for VirtioBlkService service.
type VirtioBlkServiceServer interface {
	VirtioBlkCreate(context.Context, *VirtioBlkCreateRequest) (*VirtioBlkCreateResponse, error)
	VirtioBlkDelete(context.Context, *VirtioBlkDeleteRequest) (*VirtioBlkDeleteResponse, error)
	VirtioBlkUpdate(context.Context, *VirtioBlkUpdateRequest) (*VirtioBlkUpdateResponse, error)
	VirtioBlkList(context.Context, *VirtioBlkListRequest) (*VirtioBlkListResponse, error)
	VirtioBlkGet(context.Context, *VirtioBlkGetRequest) (*VirtioBlkGetResponse, error)
	VirtioBlkStats(context.Context, *VirtioBlkStatsRequest) (*VirtioBlkStatsResponse, error)
}

// UnimplementedVirtioBlkServiceServer can be embedded to have forward compatible implementations.
type UnimplementedVirtioBlkServiceServer struct {
}

func (*UnimplementedVirtioBlkServiceServer) VirtioBlkCreate(context.Context, *VirtioBlkCreateRequest) (*VirtioBlkCreateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method VirtioBlkCreate not implemented")
}
func (*UnimplementedVirtioBlkServiceServer) VirtioBlkDelete(context.Context, *VirtioBlkDeleteRequest) (*VirtioBlkDeleteResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method VirtioBlkDelete not implemented")
}
func (*UnimplementedVirtioBlkServiceServer) VirtioBlkUpdate(context.Context, *VirtioBlkUpdateRequest) (*VirtioBlkUpdateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method VirtioBlkUpdate not implemented")
}
func (*UnimplementedVirtioBlkServiceServer) VirtioBlkList(context.Context, *VirtioBlkListRequest) (*VirtioBlkListResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method VirtioBlkList not implemented")
}
func (*UnimplementedVirtioBlkServiceServer) VirtioBlkGet(context.Context, *VirtioBlkGetRequest) (*VirtioBlkGetResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method VirtioBlkGet not implemented")
}
func (*UnimplementedVirtioBlkServiceServer) VirtioBlkStats(context.Context, *VirtioBlkStatsRequest) (*VirtioBlkStatsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method VirtioBlkStats not implemented")
}

func RegisterVirtioBlkServiceServer(s *grpc.Server, srv VirtioBlkServiceServer) {
	s.RegisterService(&_VirtioBlkService_serviceDesc, srv)
}

func _VirtioBlkService_VirtioBlkCreate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VirtioBlkCreateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VirtioBlkServiceServer).VirtioBlkCreate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/opi.storage.v1.VirtioBlkService/VirtioBlkCreate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VirtioBlkServiceServer).VirtioBlkCreate(ctx, req.(*VirtioBlkCreateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VirtioBlkService_VirtioBlkDelete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VirtioBlkDeleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VirtioBlkServiceServer).VirtioBlkDelete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/opi.storage.v1.VirtioBlkService/VirtioBlkDelete",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VirtioBlkServiceServer).VirtioBlkDelete(ctx, req.(*VirtioBlkDeleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VirtioBlkService_VirtioBlkUpdate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VirtioBlkUpdateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VirtioBlkServiceServer).VirtioBlkUpdate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/opi.storage.v1.VirtioBlkService/VirtioBlkUpdate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VirtioBlkServiceServer).VirtioBlkUpdate(ctx, req.(*VirtioBlkUpdateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VirtioBlkService_VirtioBlkList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VirtioBlkListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VirtioBlkServiceServer).VirtioBlkList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/opi.storage.v1.VirtioBlkService/VirtioBlkList",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VirtioBlkServiceServer).VirtioBlkList(ctx, req.(*VirtioBlkListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VirtioBlkService_VirtioBlkGet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VirtioBlkGetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VirtioBlkServiceServer).VirtioBlkGet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/opi.storage.v1.VirtioBlkService/VirtioBlkGet",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VirtioBlkServiceServer).VirtioBlkGet(ctx, req.(*VirtioBlkGetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VirtioBlkService_VirtioBlkStats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VirtioBlkStatsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VirtioBlkServiceServer).VirtioBlkStats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/opi.storage.v1.VirtioBlkService/VirtioBlkStats",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VirtioBlkServiceServer).VirtioBlkStats(ctx, req.(*VirtioBlkStatsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _VirtioBlkService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "opi.storage.v1.VirtioBlkService",
	HandlerType: (*VirtioBlkServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "VirtioBlkCreate",
			Handler:    _VirtioBlkService_VirtioBlkCreate_Handler,
		},
		{
			MethodName: "VirtioBlkDelete",
			Handler:    _VirtioBlkService_VirtioBlkDelete_Handler,
		},
		{
			MethodName: "VirtioBlkUpdate",
			Handler:    _VirtioBlkService_VirtioBlkUpdate_Handler,
		},
		{
			MethodName: "VirtioBlkList",
			Handler:    _VirtioBlkService_VirtioBlkList_Handler,
		},
		{
			MethodName: "VirtioBlkGet",
			Handler:    _VirtioBlkService_VirtioBlkGet_Handler,
		},
		{
			MethodName: "VirtioBlkStats",
			Handler:    _VirtioBlkService_VirtioBlkStats_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "frontend-virtio-blk.proto",
}
