# SPDX-License-Identifier: Apache-2.0
# Copyright (C) 2022 Intel Corporation
# Copyright (c) 2022 Dell Inc, or its subsidiaries.
# Copyright (C) 2023 Nordix Foundation.

all:
	cd opinetcommon && $(MAKE)
	cd cloud && $(MAKE)
	cd evpn-gw && $(MAKE)
	cd telco && $(MAKE)
	cd k8s && $(MAKE)
