@startmindmap
+ IPU/DPU Networking
++ NIC Mode
+++ Parameter Config
++++ MTU
++++ IP Addressing
+++++ IP Address(es)
+++++ Gateway
+++ VNIC
++ Switch/Router Mode
+++ Cloud
+++ Bridge
+++ VRF
+++ VPN/EVPN
+++ ECMP
+++ LACP
+++ BFD
++ K8s Networking
+++ Dataplane API
++++ Calico
++++ Openshift
+++ K8s Offload
+++ Secondary Network Offload
++ Offload Services
+++ Firewall
+++ SONiC/DASH
++ Network Virtualization
+++ OVS
-- Tunneling
--- VLAN
--- VXLAN
--- VTEP
--- IPSec
--- Geneve
-- QoS
--- Rate Limiting
--- Policing
--- Scheduling
-- Policy
--- Security Groups
--- IP Tables
--- NAT
-- Security
--- Cryptography
--- TLS Offload
-- Telemetry / Logging
@endmindmap
