@startuml OpenConfig-Model.plantuml
@startmindmap
+ DPU_Network_Device
++ Network Instance
+++ vlans
+++ routing
+++ vrf
+++ source routing (sr)
+++ pbr
+++ protocols
++++ local
+++++ static
+++++ aggregate
++++ bgp
++++ ospf
++++ is-is
++ Routing Policy
++ Interfaces
+++ IPv4
+++ IPv6
+++ Ethernet
+++ lag
-- L2
--- lldp
--- lacp
--- stp
-- platform
-- system
--- aaa
--- telemetry
-- acl
-- qos
@endmindmap
@enduml