@startmindmap
* Device
** Front End (host)
*** NVMe Subsystem
*** NVMe Controller
*** NVMe Namespace
** Middle End (Storage Services)
*** Compression
*** RAID (across storage backends)
*** DARE (Data at Rest Encryption)
*** QoS (Min and Max Iops and BW)
*** others...
** BackEnd (fabric)
*** NVMe
**** PCIe
**** TCP
***** ipv4
***** ipv6
**** RDMA
***** ipv4
***** ipv6
*** iSCSI
**** ipv4
**** ipv6
*** Null
*** AIO
*** Memory
** System
*** telemetry
*** log
*** statsistics
@endmindmap
